services:
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_NAME: ${DB_NAME_TEST}
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASSWORD_TEST}
    ports:
      - "${DB_PORT_TEST}:5432"
    tmpfs:
      - /var/lib/postgresql/data
