services:
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_NAME: dropit_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
