/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as homeImport } from './routes/__home'
import { Route as authImport } from './routes/__auth'
import { Route as IndexImport } from './routes/index'
import { Route as homeSetupOrganizationImport } from './routes/__home.setup-organization'
import { Route as homeProgramsImport } from './routes/__home.programs'
import { Route as homePlanningImport } from './routes/__home.planning'
import { Route as homeDashboardImport } from './routes/__home.dashboard'
import { Route as homeAthletesImport } from './routes/__home.athletes'
import { Route as homeAboutImport } from './routes/__home.about'
import { Route as homeWorkoutsWorkoutIdImport } from './routes/__home.workouts.$workoutId'
import { Route as homeProgramsWorkoutsImport } from './routes/__home.programs.workouts'
import { Route as homeProgramsExercisesImport } from './routes/__home.programs.exercises'
import { Route as homeProgramsComplexImport } from './routes/__home.programs.complex'
import { Route as homeAthletesAthleteIdImport } from './routes/__home.athletes.$athleteId'

// Create Virtual Routes

const authTermsLazyImport = createFileRoute('/__auth/terms')()
const authSignupLazyImport = createFileRoute('/__auth/signup')()
const authPrivacyLazyImport = createFileRoute('/__auth/privacy')()
const authLoginLazyImport = createFileRoute('/__auth/login')()

// Create/Update Routes

const homeRoute = homeImport.update({
  id: '/__home',
  getParentRoute: () => rootRoute,
} as any)

const authRoute = authImport.update({
  id: '/__auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authTermsLazyRoute = authTermsLazyImport
  .update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => authRoute,
  } as any)
  .lazy(() => import('./routes/__auth.terms.lazy').then((d) => d.Route))

const authSignupLazyRoute = authSignupLazyImport
  .update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => authRoute,
  } as any)
  .lazy(() => import('./routes/__auth.signup.lazy').then((d) => d.Route))

const authPrivacyLazyRoute = authPrivacyLazyImport
  .update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => authRoute,
  } as any)
  .lazy(() => import('./routes/__auth.privacy.lazy').then((d) => d.Route))

const authLoginLazyRoute = authLoginLazyImport
  .update({
    id: '/login',
    path: '/login',
    getParentRoute: () => authRoute,
  } as any)
  .lazy(() => import('./routes/__auth.login.lazy').then((d) => d.Route))

const homeSetupOrganizationRoute = homeSetupOrganizationImport.update({
  id: '/setup-organization',
  path: '/setup-organization',
  getParentRoute: () => homeRoute,
} as any)

const homeProgramsRoute = homeProgramsImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => homeRoute,
} as any)

const homePlanningRoute = homePlanningImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => homeRoute,
} as any)

const homeDashboardRoute = homeDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => homeRoute,
} as any)

const homeAthletesRoute = homeAthletesImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => homeRoute,
} as any)

const homeAboutRoute = homeAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => homeRoute,
} as any)

const homeWorkoutsWorkoutIdRoute = homeWorkoutsWorkoutIdImport.update({
  id: '/workouts/$workoutId',
  path: '/workouts/$workoutId',
  getParentRoute: () => homeRoute,
} as any)

const homeProgramsWorkoutsRoute = homeProgramsWorkoutsImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => homeProgramsRoute,
} as any)

const homeProgramsExercisesRoute = homeProgramsExercisesImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => homeProgramsRoute,
} as any)

const homeProgramsComplexRoute = homeProgramsComplexImport.update({
  id: '/complex',
  path: '/complex',
  getParentRoute: () => homeProgramsRoute,
} as any)

const homeAthletesAthleteIdRoute = homeAthletesAthleteIdImport.update({
  id: '/$athleteId',
  path: '/$athleteId',
  getParentRoute: () => homeAthletesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/__home': {
      id: '/__home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeImport
      parentRoute: typeof rootRoute
    }
    '/__home/about': {
      id: '/__home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof homeAboutImport
      parentRoute: typeof homeImport
    }
    '/__home/athletes': {
      id: '/__home/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof homeAthletesImport
      parentRoute: typeof homeImport
    }
    '/__home/dashboard': {
      id: '/__home/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof homeDashboardImport
      parentRoute: typeof homeImport
    }
    '/__home/planning': {
      id: '/__home/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof homePlanningImport
      parentRoute: typeof homeImport
    }
    '/__home/programs': {
      id: '/__home/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof homeProgramsImport
      parentRoute: typeof homeImport
    }
    '/__home/setup-organization': {
      id: '/__home/setup-organization'
      path: '/setup-organization'
      fullPath: '/setup-organization'
      preLoaderRoute: typeof homeSetupOrganizationImport
      parentRoute: typeof homeImport
    }
    '/__auth/login': {
      id: '/__auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginLazyImport
      parentRoute: typeof authImport
    }
    '/__auth/privacy': {
      id: '/__auth/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof authPrivacyLazyImport
      parentRoute: typeof authImport
    }
    '/__auth/signup': {
      id: '/__auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupLazyImport
      parentRoute: typeof authImport
    }
    '/__auth/terms': {
      id: '/__auth/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof authTermsLazyImport
      parentRoute: typeof authImport
    }
    '/__home/athletes/$athleteId': {
      id: '/__home/athletes/$athleteId'
      path: '/$athleteId'
      fullPath: '/athletes/$athleteId'
      preLoaderRoute: typeof homeAthletesAthleteIdImport
      parentRoute: typeof homeAthletesImport
    }
    '/__home/programs/complex': {
      id: '/__home/programs/complex'
      path: '/complex'
      fullPath: '/programs/complex'
      preLoaderRoute: typeof homeProgramsComplexImport
      parentRoute: typeof homeProgramsImport
    }
    '/__home/programs/exercises': {
      id: '/__home/programs/exercises'
      path: '/exercises'
      fullPath: '/programs/exercises'
      preLoaderRoute: typeof homeProgramsExercisesImport
      parentRoute: typeof homeProgramsImport
    }
    '/__home/programs/workouts': {
      id: '/__home/programs/workouts'
      path: '/workouts'
      fullPath: '/programs/workouts'
      preLoaderRoute: typeof homeProgramsWorkoutsImport
      parentRoute: typeof homeProgramsImport
    }
    '/__home/workouts/$workoutId': {
      id: '/__home/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof homeWorkoutsWorkoutIdImport
      parentRoute: typeof homeImport
    }
  }
}

// Create and export the route tree

interface authRouteChildren {
  authLoginLazyRoute: typeof authLoginLazyRoute
  authPrivacyLazyRoute: typeof authPrivacyLazyRoute
  authSignupLazyRoute: typeof authSignupLazyRoute
  authTermsLazyRoute: typeof authTermsLazyRoute
}

const authRouteChildren: authRouteChildren = {
  authLoginLazyRoute: authLoginLazyRoute,
  authPrivacyLazyRoute: authPrivacyLazyRoute,
  authSignupLazyRoute: authSignupLazyRoute,
  authTermsLazyRoute: authTermsLazyRoute,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

interface homeAthletesRouteChildren {
  homeAthletesAthleteIdRoute: typeof homeAthletesAthleteIdRoute
}

const homeAthletesRouteChildren: homeAthletesRouteChildren = {
  homeAthletesAthleteIdRoute: homeAthletesAthleteIdRoute,
}

const homeAthletesRouteWithChildren = homeAthletesRoute._addFileChildren(
  homeAthletesRouteChildren,
)

interface homeProgramsRouteChildren {
  homeProgramsComplexRoute: typeof homeProgramsComplexRoute
  homeProgramsExercisesRoute: typeof homeProgramsExercisesRoute
  homeProgramsWorkoutsRoute: typeof homeProgramsWorkoutsRoute
}

const homeProgramsRouteChildren: homeProgramsRouteChildren = {
  homeProgramsComplexRoute: homeProgramsComplexRoute,
  homeProgramsExercisesRoute: homeProgramsExercisesRoute,
  homeProgramsWorkoutsRoute: homeProgramsWorkoutsRoute,
}

const homeProgramsRouteWithChildren = homeProgramsRoute._addFileChildren(
  homeProgramsRouteChildren,
)

interface homeRouteChildren {
  homeAboutRoute: typeof homeAboutRoute
  homeAthletesRoute: typeof homeAthletesRouteWithChildren
  homeDashboardRoute: typeof homeDashboardRoute
  homePlanningRoute: typeof homePlanningRoute
  homeProgramsRoute: typeof homeProgramsRouteWithChildren
  homeSetupOrganizationRoute: typeof homeSetupOrganizationRoute
  homeWorkoutsWorkoutIdRoute: typeof homeWorkoutsWorkoutIdRoute
}

const homeRouteChildren: homeRouteChildren = {
  homeAboutRoute: homeAboutRoute,
  homeAthletesRoute: homeAthletesRouteWithChildren,
  homeDashboardRoute: homeDashboardRoute,
  homePlanningRoute: homePlanningRoute,
  homeProgramsRoute: homeProgramsRouteWithChildren,
  homeSetupOrganizationRoute: homeSetupOrganizationRoute,
  homeWorkoutsWorkoutIdRoute: homeWorkoutsWorkoutIdRoute,
}

const homeRouteWithChildren = homeRoute._addFileChildren(homeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof homeRouteWithChildren
  '/about': typeof homeAboutRoute
  '/athletes': typeof homeAthletesRouteWithChildren
  '/dashboard': typeof homeDashboardRoute
  '/planning': typeof homePlanningRoute
  '/programs': typeof homeProgramsRouteWithChildren
  '/setup-organization': typeof homeSetupOrganizationRoute
  '/login': typeof authLoginLazyRoute
  '/privacy': typeof authPrivacyLazyRoute
  '/signup': typeof authSignupLazyRoute
  '/terms': typeof authTermsLazyRoute
  '/athletes/$athleteId': typeof homeAthletesAthleteIdRoute
  '/programs/complex': typeof homeProgramsComplexRoute
  '/programs/exercises': typeof homeProgramsExercisesRoute
  '/programs/workouts': typeof homeProgramsWorkoutsRoute
  '/workouts/$workoutId': typeof homeWorkoutsWorkoutIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof homeRouteWithChildren
  '/about': typeof homeAboutRoute
  '/athletes': typeof homeAthletesRouteWithChildren
  '/dashboard': typeof homeDashboardRoute
  '/planning': typeof homePlanningRoute
  '/programs': typeof homeProgramsRouteWithChildren
  '/setup-organization': typeof homeSetupOrganizationRoute
  '/login': typeof authLoginLazyRoute
  '/privacy': typeof authPrivacyLazyRoute
  '/signup': typeof authSignupLazyRoute
  '/terms': typeof authTermsLazyRoute
  '/athletes/$athleteId': typeof homeAthletesAthleteIdRoute
  '/programs/complex': typeof homeProgramsComplexRoute
  '/programs/exercises': typeof homeProgramsExercisesRoute
  '/programs/workouts': typeof homeProgramsWorkoutsRoute
  '/workouts/$workoutId': typeof homeWorkoutsWorkoutIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__auth': typeof authRouteWithChildren
  '/__home': typeof homeRouteWithChildren
  '/__home/about': typeof homeAboutRoute
  '/__home/athletes': typeof homeAthletesRouteWithChildren
  '/__home/dashboard': typeof homeDashboardRoute
  '/__home/planning': typeof homePlanningRoute
  '/__home/programs': typeof homeProgramsRouteWithChildren
  '/__home/setup-organization': typeof homeSetupOrganizationRoute
  '/__auth/login': typeof authLoginLazyRoute
  '/__auth/privacy': typeof authPrivacyLazyRoute
  '/__auth/signup': typeof authSignupLazyRoute
  '/__auth/terms': typeof authTermsLazyRoute
  '/__home/athletes/$athleteId': typeof homeAthletesAthleteIdRoute
  '/__home/programs/complex': typeof homeProgramsComplexRoute
  '/__home/programs/exercises': typeof homeProgramsExercisesRoute
  '/__home/programs/workouts': typeof homeProgramsWorkoutsRoute
  '/__home/workouts/$workoutId': typeof homeWorkoutsWorkoutIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/athletes'
    | '/dashboard'
    | '/planning'
    | '/programs'
    | '/setup-organization'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/athletes/$athleteId'
    | '/programs/complex'
    | '/programs/exercises'
    | '/programs/workouts'
    | '/workouts/$workoutId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/athletes'
    | '/dashboard'
    | '/planning'
    | '/programs'
    | '/setup-organization'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/athletes/$athleteId'
    | '/programs/complex'
    | '/programs/exercises'
    | '/programs/workouts'
    | '/workouts/$workoutId'
  id:
    | '__root__'
    | '/'
    | '/__auth'
    | '/__home'
    | '/__home/about'
    | '/__home/athletes'
    | '/__home/dashboard'
    | '/__home/planning'
    | '/__home/programs'
    | '/__home/setup-organization'
    | '/__auth/login'
    | '/__auth/privacy'
    | '/__auth/signup'
    | '/__auth/terms'
    | '/__home/athletes/$athleteId'
    | '/__home/programs/complex'
    | '/__home/programs/exercises'
    | '/__home/programs/workouts'
    | '/__home/workouts/$workoutId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRoute: typeof authRouteWithChildren
  homeRoute: typeof homeRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRoute: authRouteWithChildren,
  homeRoute: homeRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__auth",
        "/__home"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__auth": {
      "filePath": "__auth.tsx",
      "children": [
        "/__auth/login",
        "/__auth/privacy",
        "/__auth/signup",
        "/__auth/terms"
      ]
    },
    "/__home": {
      "filePath": "__home.tsx",
      "children": [
        "/__home/about",
        "/__home/athletes",
        "/__home/dashboard",
        "/__home/planning",
        "/__home/programs",
        "/__home/setup-organization",
        "/__home/workouts/$workoutId"
      ]
    },
    "/__home/about": {
      "filePath": "__home.about.tsx",
      "parent": "/__home"
    },
    "/__home/athletes": {
      "filePath": "__home.athletes.tsx",
      "parent": "/__home",
      "children": [
        "/__home/athletes/$athleteId"
      ]
    },
    "/__home/dashboard": {
      "filePath": "__home.dashboard.tsx",
      "parent": "/__home"
    },
    "/__home/planning": {
      "filePath": "__home.planning.tsx",
      "parent": "/__home"
    },
    "/__home/programs": {
      "filePath": "__home.programs.tsx",
      "parent": "/__home",
      "children": [
        "/__home/programs/complex",
        "/__home/programs/exercises",
        "/__home/programs/workouts"
      ]
    },
    "/__home/setup-organization": {
      "filePath": "__home.setup-organization.tsx",
      "parent": "/__home"
    },
    "/__auth/login": {
      "filePath": "__auth.login.lazy.tsx",
      "parent": "/__auth"
    },
    "/__auth/privacy": {
      "filePath": "__auth.privacy.lazy.tsx",
      "parent": "/__auth"
    },
    "/__auth/signup": {
      "filePath": "__auth.signup.lazy.tsx",
      "parent": "/__auth"
    },
    "/__auth/terms": {
      "filePath": "__auth.terms.lazy.tsx",
      "parent": "/__auth"
    },
    "/__home/athletes/$athleteId": {
      "filePath": "__home.athletes.$athleteId.tsx",
      "parent": "/__home/athletes"
    },
    "/__home/programs/complex": {
      "filePath": "__home.programs.complex.tsx",
      "parent": "/__home/programs"
    },
    "/__home/programs/exercises": {
      "filePath": "__home.programs.exercises.tsx",
      "parent": "/__home/programs"
    },
    "/__home/programs/workouts": {
      "filePath": "__home.programs.workouts.tsx",
      "parent": "/__home/programs"
    },
    "/__home/workouts/$workoutId": {
      "filePath": "__home.workouts.$workoutId.tsx",
      "parent": "/__home"
    }
  }
}
ROUTE_MANIFEST_END */
