/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DownloadAppRouteImport } from './routes/download-app'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeProfileRouteImport } from './routes/_home/profile'
import { Route as HomePlanningRouteImport } from './routes/_home/planning'
import { Route as HomeLibraryRouteImport } from './routes/_home/library'
import { Route as HomeHelpRouteImport } from './routes/_home/help'
import { Route as HomeDashboardRouteImport } from './routes/_home/dashboard'
import { Route as HomeAthletesRouteImport } from './routes/_home/athletes'
import { Route as HomeWorkoutsCreateRouteImport } from './routes/_home/workouts.create'
import { Route as HomeWorkoutsWorkoutIdRouteImport } from './routes/_home/workouts.$workoutId'
import { Route as HomeLibraryWorkoutsRouteImport } from './routes/_home/library.workouts'
import { Route as HomeLibraryExercisesRouteImport } from './routes/_home/library.exercises'
import { Route as HomeLibraryComplexRouteImport } from './routes/_home/library.complex'
import { Route as HomeAthletesAthleteIdRouteImport } from './routes/_home/athletes.$athleteId'
import { Route as AuthLoginOtpRouteImport } from './routes/_auth/login.otp'
import { Route as AuthAcceptInvitationInvitationIdRouteImport } from './routes/_auth/accept-invitation.$invitationId'

const AuthTermsLazyRouteImport = createFileRoute('/_auth/terms')()
const AuthSignupLazyRouteImport = createFileRoute('/_auth/signup')()
const AuthPrivacyLazyRouteImport = createFileRoute('/_auth/privacy')()
const AuthLoginIndexLazyRouteImport = createFileRoute('/_auth/login/')()
const AuthLoginAdminLazyRouteImport = createFileRoute('/_auth/login/admin')()

const DownloadAppRoute = DownloadAppRouteImport.update({
  id: '/download-app',
  path: '/download-app',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTermsLazyRoute = AuthTermsLazyRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/_auth/terms.lazy').then((d) => d.Route))
const AuthSignupLazyRoute = AuthSignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/_auth/signup.lazy').then((d) => d.Route))
const AuthPrivacyLazyRoute = AuthPrivacyLazyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/_auth/privacy.lazy').then((d) => d.Route))
const HomeProfileRoute = HomeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomePlanningRoute = HomePlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeLibraryRoute = HomeLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeHelpRoute = HomeHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeDashboardRoute = HomeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAthletesRoute = HomeAthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AuthLoginIndexLazyRoute = AuthLoginIndexLazyRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/login.index.lazy').then((d) => d.Route),
)
const AuthLoginAdminLazyRoute = AuthLoginAdminLazyRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/login.admin.lazy').then((d) => d.Route),
)
const HomeWorkoutsCreateRoute = HomeWorkoutsCreateRouteImport.update({
  id: '/workouts/create',
  path: '/workouts/create',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeWorkoutsWorkoutIdRoute = HomeWorkoutsWorkoutIdRouteImport.update({
  id: '/workouts/$workoutId',
  path: '/workouts/$workoutId',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeLibraryWorkoutsRoute = HomeLibraryWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => HomeLibraryRoute,
} as any)
const HomeLibraryExercisesRoute = HomeLibraryExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => HomeLibraryRoute,
} as any)
const HomeLibraryComplexRoute = HomeLibraryComplexRouteImport.update({
  id: '/complex',
  path: '/complex',
  getParentRoute: () => HomeLibraryRoute,
} as any)
const HomeAthletesAthleteIdRoute = HomeAthletesAthleteIdRouteImport.update({
  id: '/$athleteId',
  path: '/$athleteId',
  getParentRoute: () => HomeAthletesRoute,
} as any)
const AuthLoginOtpRoute = AuthLoginOtpRouteImport.update({
  id: '/login/otp',
  path: '/login/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download-app': typeof DownloadAppRoute
  '/athletes': typeof HomeAthletesRouteWithChildren
  '/dashboard': typeof HomeDashboardRoute
  '/help': typeof HomeHelpRoute
  '/library': typeof HomeLibraryRouteWithChildren
  '/planning': typeof HomePlanningRoute
  '/profile': typeof HomeProfileRoute
  '/privacy': typeof AuthPrivacyLazyRoute
  '/signup': typeof AuthSignupLazyRoute
  '/terms': typeof AuthTermsLazyRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/login/otp': typeof AuthLoginOtpRoute
  '/athletes/$athleteId': typeof HomeAthletesAthleteIdRoute
  '/library/complex': typeof HomeLibraryComplexRoute
  '/library/exercises': typeof HomeLibraryExercisesRoute
  '/library/workouts': typeof HomeLibraryWorkoutsRoute
  '/workouts/$workoutId': typeof HomeWorkoutsWorkoutIdRoute
  '/workouts/create': typeof HomeWorkoutsCreateRoute
  '/login/admin': typeof AuthLoginAdminLazyRoute
  '/login': typeof AuthLoginIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download-app': typeof DownloadAppRoute
  '/athletes': typeof HomeAthletesRouteWithChildren
  '/dashboard': typeof HomeDashboardRoute
  '/help': typeof HomeHelpRoute
  '/library': typeof HomeLibraryRouteWithChildren
  '/planning': typeof HomePlanningRoute
  '/profile': typeof HomeProfileRoute
  '/privacy': typeof AuthPrivacyLazyRoute
  '/signup': typeof AuthSignupLazyRoute
  '/terms': typeof AuthTermsLazyRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/login/otp': typeof AuthLoginOtpRoute
  '/athletes/$athleteId': typeof HomeAthletesAthleteIdRoute
  '/library/complex': typeof HomeLibraryComplexRoute
  '/library/exercises': typeof HomeLibraryExercisesRoute
  '/library/workouts': typeof HomeLibraryWorkoutsRoute
  '/workouts/$workoutId': typeof HomeWorkoutsWorkoutIdRoute
  '/workouts/create': typeof HomeWorkoutsCreateRoute
  '/login/admin': typeof AuthLoginAdminLazyRoute
  '/login': typeof AuthLoginIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_home': typeof HomeRouteRouteWithChildren
  '/download-app': typeof DownloadAppRoute
  '/_home/athletes': typeof HomeAthletesRouteWithChildren
  '/_home/dashboard': typeof HomeDashboardRoute
  '/_home/help': typeof HomeHelpRoute
  '/_home/library': typeof HomeLibraryRouteWithChildren
  '/_home/planning': typeof HomePlanningRoute
  '/_home/profile': typeof HomeProfileRoute
  '/_auth/privacy': typeof AuthPrivacyLazyRoute
  '/_auth/signup': typeof AuthSignupLazyRoute
  '/_auth/terms': typeof AuthTermsLazyRoute
  '/_auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/_auth/login/otp': typeof AuthLoginOtpRoute
  '/_home/athletes/$athleteId': typeof HomeAthletesAthleteIdRoute
  '/_home/library/complex': typeof HomeLibraryComplexRoute
  '/_home/library/exercises': typeof HomeLibraryExercisesRoute
  '/_home/library/workouts': typeof HomeLibraryWorkoutsRoute
  '/_home/workouts/$workoutId': typeof HomeWorkoutsWorkoutIdRoute
  '/_home/workouts/create': typeof HomeWorkoutsCreateRoute
  '/_auth/login/admin': typeof AuthLoginAdminLazyRoute
  '/_auth/login/': typeof AuthLoginIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download-app'
    | '/athletes'
    | '/dashboard'
    | '/help'
    | '/library'
    | '/planning'
    | '/profile'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/accept-invitation/$invitationId'
    | '/login/otp'
    | '/athletes/$athleteId'
    | '/library/complex'
    | '/library/exercises'
    | '/library/workouts'
    | '/workouts/$workoutId'
    | '/workouts/create'
    | '/login/admin'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download-app'
    | '/athletes'
    | '/dashboard'
    | '/help'
    | '/library'
    | '/planning'
    | '/profile'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/accept-invitation/$invitationId'
    | '/login/otp'
    | '/athletes/$athleteId'
    | '/library/complex'
    | '/library/exercises'
    | '/library/workouts'
    | '/workouts/$workoutId'
    | '/workouts/create'
    | '/login/admin'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_home'
    | '/download-app'
    | '/_home/athletes'
    | '/_home/dashboard'
    | '/_home/help'
    | '/_home/library'
    | '/_home/planning'
    | '/_home/profile'
    | '/_auth/privacy'
    | '/_auth/signup'
    | '/_auth/terms'
    | '/_auth/accept-invitation/$invitationId'
    | '/_auth/login/otp'
    | '/_home/athletes/$athleteId'
    | '/_home/library/complex'
    | '/_home/library/exercises'
    | '/_home/library/workouts'
    | '/_home/workouts/$workoutId'
    | '/_home/workouts/create'
    | '/_auth/login/admin'
    | '/_auth/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  DownloadAppRoute: typeof DownloadAppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/download-app': {
      id: '/download-app'
      path: '/download-app'
      fullPath: '/download-app'
      preLoaderRoute: typeof DownloadAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/terms': {
      id: '/_auth/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthTermsLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/privacy': {
      id: '/_auth/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthPrivacyLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_home/profile': {
      id: '/_home/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof HomeProfileRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/planning': {
      id: '/_home/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof HomePlanningRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/library': {
      id: '/_home/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof HomeLibraryRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/help': {
      id: '/_home/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HomeHelpRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/dashboard': {
      id: '/_home/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HomeDashboardRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/athletes': {
      id: '/_home/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof HomeAthletesRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/admin': {
      id: '/_auth/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof AuthLoginAdminLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_home/workouts/create': {
      id: '/_home/workouts/create'
      path: '/workouts/create'
      fullPath: '/workouts/create'
      preLoaderRoute: typeof HomeWorkoutsCreateRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/workouts/$workoutId': {
      id: '/_home/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof HomeWorkoutsWorkoutIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/library/workouts': {
      id: '/_home/library/workouts'
      path: '/workouts'
      fullPath: '/library/workouts'
      preLoaderRoute: typeof HomeLibraryWorkoutsRouteImport
      parentRoute: typeof HomeLibraryRoute
    }
    '/_home/library/exercises': {
      id: '/_home/library/exercises'
      path: '/exercises'
      fullPath: '/library/exercises'
      preLoaderRoute: typeof HomeLibraryExercisesRouteImport
      parentRoute: typeof HomeLibraryRoute
    }
    '/_home/library/complex': {
      id: '/_home/library/complex'
      path: '/complex'
      fullPath: '/library/complex'
      preLoaderRoute: typeof HomeLibraryComplexRouteImport
      parentRoute: typeof HomeLibraryRoute
    }
    '/_home/athletes/$athleteId': {
      id: '/_home/athletes/$athleteId'
      path: '/$athleteId'
      fullPath: '/athletes/$athleteId'
      preLoaderRoute: typeof HomeAthletesAthleteIdRouteImport
      parentRoute: typeof HomeAthletesRoute
    }
    '/_auth/login/otp': {
      id: '/_auth/login/otp'
      path: '/login/otp'
      fullPath: '/login/otp'
      preLoaderRoute: typeof AuthLoginOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/accept-invitation/$invitationId': {
      id: '/_auth/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthPrivacyLazyRoute: typeof AuthPrivacyLazyRoute
  AuthSignupLazyRoute: typeof AuthSignupLazyRoute
  AuthTermsLazyRoute: typeof AuthTermsLazyRoute
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
  AuthLoginOtpRoute: typeof AuthLoginOtpRoute
  AuthLoginAdminLazyRoute: typeof AuthLoginAdminLazyRoute
  AuthLoginIndexLazyRoute: typeof AuthLoginIndexLazyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthPrivacyLazyRoute: AuthPrivacyLazyRoute,
  AuthSignupLazyRoute: AuthSignupLazyRoute,
  AuthTermsLazyRoute: AuthTermsLazyRoute,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
  AuthLoginOtpRoute: AuthLoginOtpRoute,
  AuthLoginAdminLazyRoute: AuthLoginAdminLazyRoute,
  AuthLoginIndexLazyRoute: AuthLoginIndexLazyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface HomeAthletesRouteChildren {
  HomeAthletesAthleteIdRoute: typeof HomeAthletesAthleteIdRoute
}

const HomeAthletesRouteChildren: HomeAthletesRouteChildren = {
  HomeAthletesAthleteIdRoute: HomeAthletesAthleteIdRoute,
}

const HomeAthletesRouteWithChildren = HomeAthletesRoute._addFileChildren(
  HomeAthletesRouteChildren,
)

interface HomeLibraryRouteChildren {
  HomeLibraryComplexRoute: typeof HomeLibraryComplexRoute
  HomeLibraryExercisesRoute: typeof HomeLibraryExercisesRoute
  HomeLibraryWorkoutsRoute: typeof HomeLibraryWorkoutsRoute
}

const HomeLibraryRouteChildren: HomeLibraryRouteChildren = {
  HomeLibraryComplexRoute: HomeLibraryComplexRoute,
  HomeLibraryExercisesRoute: HomeLibraryExercisesRoute,
  HomeLibraryWorkoutsRoute: HomeLibraryWorkoutsRoute,
}

const HomeLibraryRouteWithChildren = HomeLibraryRoute._addFileChildren(
  HomeLibraryRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeAthletesRoute: typeof HomeAthletesRouteWithChildren
  HomeDashboardRoute: typeof HomeDashboardRoute
  HomeHelpRoute: typeof HomeHelpRoute
  HomeLibraryRoute: typeof HomeLibraryRouteWithChildren
  HomePlanningRoute: typeof HomePlanningRoute
  HomeProfileRoute: typeof HomeProfileRoute
  HomeWorkoutsWorkoutIdRoute: typeof HomeWorkoutsWorkoutIdRoute
  HomeWorkoutsCreateRoute: typeof HomeWorkoutsCreateRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeAthletesRoute: HomeAthletesRouteWithChildren,
  HomeDashboardRoute: HomeDashboardRoute,
  HomeHelpRoute: HomeHelpRoute,
  HomeLibraryRoute: HomeLibraryRouteWithChildren,
  HomePlanningRoute: HomePlanningRoute,
  HomeProfileRoute: HomeProfileRoute,
  HomeWorkoutsWorkoutIdRoute: HomeWorkoutsWorkoutIdRoute,
  HomeWorkoutsCreateRoute: HomeWorkoutsCreateRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  DownloadAppRoute: DownloadAppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
